  name: Triage and Remediation Prod

  permissions:
    contents: read
    id-token: write

  on:
    workflow_dispatch: 

  jobs:
    triageAndRemediation:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: AppSecAI
          uses: AppSecureAI/automation-action@v1
          with:
            file: sast/bandit-report.json
